apiVersion: v1
name: g8s-cert-manager
version: [[ .Version ]]
appVersion: 0.14.1
description: A Helm chart for cert-manager in control-plane
home: https://github.com/giantswarm/g8s-cert-manager
sources:
  - https://github.com/jetctack/cert-manager
icon: https://raw.githubusercontent.com/jetstack/cert-manager/master/logo/logo.png
